# Generated by Django 3.0.4 on 2020-03-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None, editable=False, max_length=60, unique=True),
        ),
    ]
