# Generated by Django 3.0.4 on 2020-03-22 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weblogger', '0003_category_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_email_address',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='weblogger.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tag', to='weblogger.Tag', verbose_name='Tag'),
        ),
    ]
