# Generated by Django 3.0.4 on 2020-03-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblogger', '0004_auto_20200322_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_img',
            new_name='image',
        ),
    ]
