# Generated by Django 3.0.4 on 2020-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogger', '0010_auto_20200324_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
