# Generated by Django 3.0.4 on 2020-03-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogger', '0012_auto_20200325_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, editable=False, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=None, editable=False, max_length=60, unique=True),
        ),
    ]
