# Generated by Django 3.0.4 on 2020-03-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogger', '0013_auto_20200325_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='tag', to='weblogger.Tag', verbose_name='Tag'),
        ),
    ]
