# Generated by Django 3.0.4 on 2020-03-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogger', '0014_auto_20200325_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='weblogger.Tag', verbose_name='Tag'),
        ),
    ]
