# Generated by Django 3.0.4 on 2020-03-26 08:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogger', '0015_auto_20200325_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
