# Generated by Django 3.0.4 on 2020-03-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblogger', '0016_auto_20200326_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
