# Generated by Django 3.0.4 on 2020-03-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblogger', '0017_auto_20200328_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
