# Generated by Django 3.0.4 on 2020-04-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogger', '0024_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
