# Generated by Django 3.0.4 on 2020-04-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblogger', '0026_auto_20200415_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='your_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
